"""
Digest renderers — convert Digest objects into deliverable formats.

Three output formats:
- Markdown: for CLI, logs, and preview
- HTML email: inline-styled for Gmail/Outlook/Apple Mail compatibility
- Slack blocks: Block Kit JSON for Slack webhooks

All renderers are pure functions: Digest in, string/dict out.
No side effects, no network calls.
"""

from __future__ import annotations

import json
from typing import Any

from digest.composer import Digest, DigestInsight


# ─── Severity styling ───

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "info": "ℹ️",
}

_SEVERITY_COLOR = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#ca8a04",
    "low": "#16a34a",
    "info": "#6b7280",
}

_SEVERITY_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


# ═══════════════════════════════════════════════════════════════════════
# Markdown Renderer
# ═══════════════════════════════════════════════════════════════════════


def render_markdown(digest: Digest) -> str:
    """Render digest as markdown text."""
    lines: list[str] = []

    # Header
    title = "Product Insights Digest"
    if digest.tenant_name:
        title = f"{digest.tenant_name} — {title}"
    lines.append(f"# {title}")
    lines.append(f"**Period:** {digest.period_label}")
    lines.append("")

    if not digest.has_insights:
        lines.append("✅ **No significant findings this period.**")
        lines.append("")
        lines.append(
            "All metrics are within normal ranges. "
            "No anomalies detected, retention is stable."
        )
        return "\n".join(lines)

    lines.append(
        f"Top {len(digest.insights)} of {digest.total_findings} findings:"
    )
    lines.append("")

    for insight in digest.insights:
        card = insight.card
        emoji = _SEVERITY_EMOJI.get(card.severity.value, "")
        label = _SEVERITY_LABEL.get(card.severity.value, "")

        lines.append(f"## {insight.rank}. {emoji} [{label}] {card.title}")
        lines.append("")
        lines.append(f"**Finding:** {card.finding}")
        lines.append("")
        lines.append(f"**Evidence:** {card.evidence}")
        lines.append("")
        lines.append(f"**Action:** {card.action}")
        lines.append("")
        if card.estimated_impact:
            lines.append(f"**Estimated Impact:** {card.estimated_impact}")
            lines.append("")
        lines.append(
            f"*Confidence: {card.confidence:.0%} · Category: {card.category}*"
        )

        if insight.feedback_url:
            lines.append("")
            lines.append(
                f"[Was this useful?]({insight.feedback_url})"
            )

        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
# HTML Email Renderer
# ═══════════════════════════════════════════════════════════════════════

# All styles are inline for email client compatibility (no <style> blocks).


def render_html_email(digest: Digest) -> str:
    """Render digest as inline-styled HTML email."""
    title = "Product Insights Digest"
    if digest.tenant_name:
        title = f"{digest.tenant_name} — {title}"

    cards_html = ""
    if digest.has_insights:
        for insight in digest.insights:
            cards_html += _render_insight_card_html(insight)
    else:
        cards_html = _render_no_insights_html()

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f4f6;">
<tr><td align="center" style="padding:24px 16px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

<!-- Header -->
<tr><td style="background-color:#1e293b;padding:24px 32px;">
<h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:600;">{title}</h1>
<p style="margin:8px 0 0;color:#94a3b8;font-size:14px;">{digest.period_label}</p>
</td></tr>

<!-- Content -->
<tr><td style="padding:24px 32px;">
{cards_html}
</td></tr>

<!-- Footer -->
<tr><td style="padding:16px 32px;border-top:1px solid #e5e7eb;">
<p style="margin:0;color:#9ca3af;font-size:12px;">
Generated by Quorum Insights · {digest.generated_at[:10]}
</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>"""


def _render_insight_card_html(insight: DigestInsight) -> str:
    card = insight.card
    color = _SEVERITY_COLOR.get(card.severity.value, "#6b7280")
    label = _SEVERITY_LABEL.get(card.severity.value, "")

    feedback_html = ""
    if insight.feedback_url:
        feedback_html = f"""
<p style="margin:12px 0 0;">
<a href="{insight.feedback_url}&vote=useful" style="color:#3b82f6;text-decoration:none;font-size:13px;">👍 Useful</a>
&nbsp;&nbsp;
<a href="{insight.feedback_url}&vote=not_useful" style="color:#3b82f6;text-decoration:none;font-size:13px;">👎 Not useful</a>
</p>"""

    evidence_html = ""
    if insight.evidence_url:
        evidence_html = f"""
<p style="margin:8px 0 0;">
<a href="{insight.evidence_url}" style="color:#3b82f6;text-decoration:none;font-size:13px;">View full evidence →</a>
</p>"""

    return f"""
<div style="margin-bottom:20px;border-left:4px solid {color};padding:16px 20px;background-color:#f8fafc;border-radius:0 6px 6px 0;">
<div style="display:flex;align-items:center;margin-bottom:8px;">
<span style="display:inline-block;padding:2px 8px;background-color:{color};color:#fff;border-radius:4px;font-size:11px;font-weight:600;letter-spacing:0.5px;">{label}</span>
<span style="margin-left:8px;color:#374151;font-size:15px;font-weight:600;">{card.title}</span>
</div>
<p style="margin:8px 0;color:#4b5563;font-size:14px;line-height:1.5;">{card.finding}</p>
<p style="margin:8px 0;color:#6b7280;font-size:13px;"><strong>Evidence:</strong> {card.evidence}</p>
<p style="margin:8px 0;color:#1e40af;font-size:14px;font-weight:500;">→ {card.action}</p>
{evidence_html}
{feedback_html}
</div>
"""


def _render_no_insights_html() -> str:
    return """
<div style="text-align:center;padding:32px 0;">
<p style="font-size:36px;margin:0;">✅</p>
<h2 style="margin:12px 0 8px;color:#1e293b;font-size:18px;">No significant findings this period</h2>
<p style="margin:0;color:#6b7280;font-size:14px;">
All metrics are within normal ranges. Retention is stable, no anomalies detected.
</p>
</div>
"""


# ═══════════════════════════════════════════════════════════════════════
# Slack Block Kit Renderer
# ═══════════════════════════════════════════════════════════════════════


def render_slack_blocks(digest: Digest) -> list[dict[str, Any]]:
    """Render digest as Slack Block Kit blocks.

    Returns a list of block dicts ready for the Slack API
    (chat.postMessage blocks parameter).
    """
    blocks: list[dict] = []

    # Header
    title = "Product Insights Digest"
    if digest.tenant_name:
        title = f"{digest.tenant_name} — {title}"

    blocks.append({
        "type": "header",
        "text": {"type": "plain_text", "text": title, "emoji": True},
    })
    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"📅 *{digest.period_label}*"},
        ],
    })
    blocks.append({"type": "divider"})

    if not digest.has_insights:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    "✅ *No significant findings this period.*\n"
                    "All metrics are within normal ranges. "
                    "Retention is stable, no anomalies detected."
                ),
            },
        })
        return blocks

    for insight in digest.insights:
        card = insight.card
        emoji = _SEVERITY_EMOJI.get(card.severity.value, "")
        label = _SEVERITY_LABEL.get(card.severity.value, "")

        # Insight section
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"{emoji} *[{label}] {card.title}*\n\n"
                    f"{card.finding}\n\n"
                    f"_Evidence: {card.evidence}_\n\n"
                    f"*→ {card.action}*"
                ),
            },
        })

        # Feedback actions
        if insight.feedback_url:
            blocks.append({
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "👍 Useful"},
                        "url": f"{insight.feedback_url}&vote=useful",
                        "action_id": f"feedback_useful_{insight.rank}",
                    },
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "👎 Not useful"},
                        "url": f"{insight.feedback_url}&vote=not_useful",
                        "action_id": f"feedback_not_useful_{insight.rank}",
                    },
                ],
            })

        blocks.append({"type": "divider"})

    # Footer
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"Generated by Quorum Insights · {digest.generated_at[:10]}",
            },
        ],
    })

    return blocks
