"""
InsightCard data model — the output of the LLM insight engine.

Each InsightCard is a specific, actionable finding with:
- Title: concise summary
- Severity: how urgent this is
- Finding: what the data shows
- Evidence: which stats back this up
- Action: what to do about it
- Confidence: statistical confidence (from stats layer)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class InsightSeverity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class InsightCard:
    """A single insight generated by the LLM engine."""

    title: str
    severity: InsightSeverity
    finding: str  # What the data shows
    evidence: str  # Which stats support this
    action: str  # What to do about it
    confidence: float  # 0-1, from stats layer
    category: str  # retention, anomaly, feature_correlation, etc.
    estimated_impact: Optional[str] = None  # e.g. "~5% retention improvement"
    related_metrics: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "severity": self.severity.value,
            "finding": self.finding,
            "evidence": self.evidence,
            "action": self.action,
            "confidence": round(self.confidence, 3),
            "category": self.category,
            "estimated_impact": self.estimated_impact,
            "related_metrics": self.related_metrics,
        }

    @classmethod
    def from_dict(cls, d: dict) -> InsightCard:
        return cls(
            title=d["title"],
            severity=InsightSeverity(d["severity"]),
            finding=d["finding"],
            evidence=d["evidence"],
            action=d["action"],
            confidence=d.get("confidence", 0.5),
            category=d.get("category", "unknown"),
            estimated_impact=d.get("estimated_impact"),
            related_metrics=d.get("related_metrics", []),
        )


@dataclass
class InsightResponse:
    """Full response from the insight engine."""

    cards: list[InsightCard]
    prompt_version: str
    model: str
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    cached: bool = False
    token_usage: Optional[dict] = None  # {"input": N, "output": M}

    def to_dict(self) -> dict:
        return {
            "cards": [c.to_dict() for c in self.cards],
            "prompt_version": self.prompt_version,
            "model": self.model,
            "generated_at": self.generated_at,
            "cached": self.cached,
            "token_usage": self.token_usage,
        }
